# Generated by Django 6.0 on 2026-01-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('movies', '0002_alter_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='movies.film'),
        ),
    ]
