# Generated by Django 6.0.1 on 2026-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDIE', 'Comédie'), ('DRAME', 'Drame'), ('SF', 'Science-Fiction'), ('HORREUR', 'Horreur'), ('ANIMATION', 'Dessin Animé')], max_length=50)),
                ('date_sortie', models.DateField()),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
    ]
