# Generated by Django 6.0 on 2026-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDIE', 'Comédie'), ('DRAME', 'Drame'), ('SF', 'Science-Fiction'), ('HORREUR', 'Horreur'), ('ANIMATION', 'Dessin Animé')], max_length=50),
        ),
    ]
